# MUIC_UNIVERSAL
obj-$(CONFIG_MUIC_UNIVERSAL)	        += muic_task.o
obj-$(CONFIG_MUIC_UNIVERSAL)	        += muic_state.o
obj-$(CONFIG_MUIC_UNIVERSAL)	        += muic_apis.o
obj-$(CONFIG_MUIC_UNIVERSAL)	        += muic_sysfs.o
obj-$(CONFIG_MUIC_UNIVERSAL)	        += muic_debug.o
obj-$(CONFIG_MUIC_UNIVERSAL)	        += muic_dt.o
obj-$(CONFIG_MUIC_UNIVERSAL)	        += muic_i2c.o
obj-$(CONFIG_MUIC_UNIVERSAL)	        += muic_regmap.o
obj-$(CONFIG_MUIC_UNIVERSAL)	        += muic_vps.o
obj-$(CONFIG_MUIC_UNIVERSAL_SM5703)	+= muic_regmap_sm5703.o
obj-$(CONFIG_MUIC_UNIVERSAL_S2MM001)	+= muic_regmap_s2mm001b.o
obj-$(CONFIG_MUIC_UNIVERSAL_MAX77849)	+= muic_regmap_max77849.o
